# -*- coding: utf-8 -*-
"""Moondream_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YnV1aSWXsSDCnh4unVI1IvOjClaOK5W-
"""

pip install transformers timm einops

from google.colab import drive
drive.mount('/content/drive')

from transformers import AutoModelForCausalLM, AutoTokenizer
from PIL import Image

model_id = "vikhyatk/moondream2"
revision = "2024-03-06"
model = AutoModelForCausalLM.from_pretrained(
    model_id, trust_remote_code=True, revision=revision
)
tokenizer = AutoTokenizer.from_pretrained(model_id, revision=revision)

image = Image.open(r"/content/article.png")
enc_image = model.encode_image(image)

# @title Default title text
print(model.answer_question(enc_image, "Summarize the article", tokenizer))